# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Ubuntu as a parent image
FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    libopencv-dev \
    libeigen3-dev \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Create a build directory and switch to it
RUN mkdir -p build
WORKDIR /app/build

# Run CMake to configure the project and then build it
RUN cmake .. && make

# Run the executable produced by CMake
CMD ["./main"]
